apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacrafters-generative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacrafters-generative
  template:
    metadata:
      labels:
        app: datacrafters-generative
    spec:
      containers:
      - name: datacrafters-generative-container
        image: guimaraesabri/datacrafters-generative:develop  
        imagePullPolicy: Always  
        ports:
        - containerPort: 8000  # uvicorn/FastAPI
        - containerPort: 8501  # streamlit
        env:
        - name: OPENAI_BASE
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: base
        - name: OPENAI_VERSION
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: version
        - name: OPENAI_KEY
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: key
        - name: OPENAI_TYPE
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: type
        - name: OPENAI_DEPLOYMENT_NAME
          valueFrom:
            secretKeyRef:
              name: openai-credentials
              key: deployment_name





