apiVersion: v1
kind: Pod
metadata:
  name: seu-pod
spec:
  containers:
  - name: seu-container
    image: sua-imagem
    env:
      - name: OPENAI_BASE
        valueFrom:
          secretKeyRef:
            name: openai-credentials
            key: base
      - name: OPENAI_VERSION
        valueFrom:
          secretKeyRef:
            name: openai-credentials
            key: version
      - name: OPENAI_KEY
        valueFrom:
          secretKeyRef:
            name: openai-credentials
            key: key
      - name: OPENAI_TYPE
        valueFrom:
          secretKeyRef:
            name: openai-credentials
            key: type
      - name: OPENAI_DEPLOYMENT_NAME
        valueFrom:
          secretKeyRef:
            name: openai-credentials
            key: deployment_name
