apiVersion: v1
kind: Secret
metadata:
  name: openai-credentials
type: Opaque
data:
  base: [Azure endpoint codificado em base64]
  version: [Version codificado em base64]
  key: [API key codificado em base64]
  type: [API type codificado em base64]
  deployment_name: [Deployment name codificado em base64]

