kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  selector:
    app: datacrafters-generative
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer

---
kind: Service
apiVersion: v1
metadata:
  name: streamlit-service
spec:
  selector:
    app: datacrafters-generative
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer

