apiVersion: v1
kind: Service
metadata:
  name: datacrafters-generative-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: datacrafters-generative
  ports:
    - port: 8080
      targetPort: 8080
